name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper 
  drawing_animation: ^0.1.3
  google_fonts: ^0.3.2
  flare_flutter: ^1.8.3
  liquid_progress_indicator: ^0.3.2

   
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
    - family: IronMan
      fonts:
        - asset: assets/IronMan.ttf
  assets:
  - assets/Flutter-clock.flr
  - assets/test.svg
  